version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - DASHBOARD_PASSWORD=${DASHBOARD_PASSWORD}

